version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - vars.env
    ports:
      - "5432:5432"
    volumes:
       - database:/var/lib/postgresql/data
  spring-boot-app:
    image: vdeskovski/test:4.0
    ports:
      - "8080:8080"
    env_file:
      - vars.env
    depends_on:
      - postgres

volumes:
  database:
