apiVersion: v1
kind: ConfigMap #
metadata:
  name: cm-app
  namespace: devops
data:
  POSTGRES_DB: "techshopDb"
  #POSTGRES_URL: "jdbc:postgresql://postgres:5432/techshopDb"
  POSTGRES_URL: "jdbc:postgresql://svc-db.devops.svc.cluster.local:5432/techshopDb"
  #POSTGRES_URL: "jdbc:postgresql://postgres:5432/techshopDb"
  #POSTGRES_URL: "jdbc:postgresql://svc-db:5432/techshopDb"
  POSTGRES_USER: "postgres"
---
apiVersion: v1
kind: Secret #
metadata:
  name: secret-app
  namespace: devops
data:
  POSTGRES_PASSWORD: MTIzNA==
---
apiVersion: apps/v1
kind: Deployment #
metadata:
  name: deploy-app
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-sb-app
  template:
    metadata:
      labels:
        app: java-sb-app
    spec:
      containers:
        - name: java-sb-container
          image: vdeskovski/techwarehouse:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-app
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-app
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cm-app
                  key: POSTGRES_DB
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-app
                  key: POSTGRES_URL
---
apiVersion: v1
kind: Service #
metadata:
  name: svc-app
  namespace: devops
spec:
  selector:
    app: java-sb-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


