name: docker-push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/techwarehouse:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/techwarehouse:latest
        # uses: docker/build-push-action@v5
        # with:
        #   push: true
        #   tags: ${{ secrets.DOCKERHUB_USERNAME }}/techwarehouse:latest
